### PR TITLE
Add Quantum computers talk

### LINKED ISSUE #66: Missing quantum computers talk

### PR DESCRIPTION
**Pull request by Wonskcalb**
- Adds the django training to the portal

This resolves #66

### CODE REVIEW

**Comment by Alterrien** [comment]
I trust that @neeev has already verified the video.
Should we take #59 into account, regarding the image size ?
Otherwise I'm all good !

**Comment by Wonskcalb** [comment]
Indeed, @neeev actually didn't made a comment on the video, I'm waiting his feedback. YES ! I totally forgot to take #59 into account. I'll update this right away

**Comment by Alterrien** [comment]
Well, until we actually make a decision on this, we do not really need to do anything, but providing a 854×480 thumbnail for this would reduce the amount of time needed to make the change.
For reference : `convert thumbnail.jpg -resize 854x480 thumbnail_small.jpg` does the job very well (and is what I've used on #62)

**Comment by Wonskcalb** [comment]
Thumbnail changed, as I don't think the decision we'll be taking to long to be validated. We just need some feedback but other than that, #62 _will_ be merged soon in my opinion

**Pull request merged**
