### PR TITLE
Resized large images for the thumbnails when needed

### LINKED ISSUE #59: Reduce thumbnails DPI
Especially on this page : https://learn.atilla.org/talks.html, about 8 thumbnails are loaded, each having a 1920x1080 pixels resolution. Each image then weights about 1.2 to 1.5M, which is quite a lot considering the fact that those images are just thumbnails.

This page weights then about 10M, and can degrade the browsing experience of a user far away from our servers (eg : in America) ; moreover, some people may sill have a low-data phone plan, and a 10M page could drastically reduce the amount of remaining data.

TO DO (proposed) : 
- Reduce the size of each thumbnail to a more "web compliant" resolution (eg : 854×480 pixels ; https://upload.wikimedia.org/wikipedia/commons/e/e5/Vector_Video_Standards2.svg).
- If the full-resolution image is still needed somewhere else, upload separate thumbnails.

### PR DESCRIPTION
**Pull request by Alterrien**
This PR is not to be merged right now, I'm waiting for more feedback on how the different thumbnails look on different sized screens (if somebody has a 2k-plus monitor, he's welcome to give some feedback)
I've resized the thumbnails to 854x480 using `convert $file -resize 854x480 $newfile`, which should give good enough results. Other solutions could be tried.

Cheers !

Resolves #59

### CODE REVIEW

**Comment by Wonskcalb** [comment]
Tested on my Oneplus 2 5.5" 1920*1080 display, and although layout is broken on small displays, stills render correctly.

**Comment by Alterrien** [comment]
Paging @aubincleme for input (especially for this : should we be keeping the larger-size images ?)

**Comment by aubincleme** [comment]
854x480 should be a good resolution

**Comment by aubincleme** [comment]
I think that larger-size images should be kept somewhere else, without weighing this repository.

**Comment by Wonskcalb** [comment]
cdn.atilla.org ?

**Comment by Wonskcalb** [comment]
This will let us to serve multiple size

**Comment by aubincleme** [comment]
Nope, it’s also another repository, it’s the same problem ; I think that we should keep the original images in where we actually store them (drive.google.com), and diffuse them only if needed.

**Comment by Wonskcalb** [comment]
I do not agree on this. This website will certainly need a some point higher DPI version of those images if the website is shown on a high DPI screen

**Comment by aubincleme** [comment]
Ok, let’s make some calculations here : 
- Let’s consider that the industry standard in terms of screen resolution is 4K (even if it’s not the case **at all**)
- We can display about 10 conference / talk / author «rows» on a 4K screen
- In each row, the thumbnail takes about 1/12 of the page width
- The native 4K resolution is 4 096 × 2 160

With all this, we can calculate an approximation of the minimal resolution of a thumbnail in this configuration : 

`4096 * (1/12) ~= 340`
`2160 * (1/10) = 216`

There you have it, in order to be correctly displayed on a 4K screen, a thumbnail should have a resolution greater than 340*216

**So,** 
Will the website need high-DPI thumbnails at some point ? **Maybe**
Should we prepare for this ? **Certainly not** ; we will be able to add high-DPI images in the future anyway.

**Comment by Wonskcalb** [comment]
I'm not telling do this now. Certainly not. Re-read what I've written. I just meant to say the cdn will be the way to go. It is supposed to, in any matter. I've proposed the High-DPI version here #60. Period.

**Comment by Alterrien** [comment]
So, we actually need to come to a decision : I guess the image resolution is good, but what will we do with the higher-res images ? Do we have a backup of them somewhere else ? Could we use our OwnCloud to store them ?

**Comment by Wonskcalb** [comment]
We already have backups of those images oh the Google drive of the comm team. We can delete those safely

**Comment by Alterrien** [comment]
Alright, I'll delete the Hi-res files and merge after lunch.

**Comment by Wonskcalb** [comment]
I can do this right now, it won't take long

**Pull request merged**
