### PR TITLE
Add a list of authors with list of events authored

### PR DESCRIPTION
**Pull request by Wonskcalb**
Hey there, 

Added a list of authors with a page behind showing author with authored projects

### CODE REVIEW

**Comment by Wonskcalb** [comment]
cc @Thooms

**Comment by Thooms** [comment]
In a specific author page, better remove the talk/conf/etc description out and print it on click, after the animation. Also, on my computer the design is kinda broken: https://imgur.com/9YQlo6X 
Perhaps it could be cool to add a link to an author's page on the author thumbnail (in a talk/conf page)

**Comment by Wonskcalb** [comment]
Yep I thought of adding links to authors in talks/conf/... I'll look at the broken layout. Short description is shown, with full description on click, do you feel like I should remove the short one ?

**Comment by Wonskcalb** [comment]
Good for review @flavray

**Pull request merged**
