### PR TITLE
Change favicon path

### PR DESCRIPTION
**Pull request by florent1933**

### CODE REVIEW

**Comment by Thooms** [comment]
Hm, pulling a favicon from another site? It's a bit dirty. I suggest we copy it here for now, and see later for some kind of Atilla CDN.

**Comment by florent1933** [comment]
I dislike the idea of copying images. Prefer to use a favicon from another site.

**Comment by Thooms** [comment]
@flavray @MrChoclate any thought about that?

**Comment by MrChoclate** [comment]
I vote for a copy or CDN but not from atilla.org

**Comment by Thooms** [comment]
<3

**Comment by florent1933** [comment]
I vote for CDN. Who take in charge the CDN development?

**Comment by Thooms** [comment]
Well for now let's simply duplicate the image, we got enough on our plates for now, we'll code the CDN later.

**Comment by florent1933** [comment]
How many time to have a CDN?

**Comment by florent1933** [comment]
I will not duplicate the image, I dislike the idea

**Comment by MrChoclate** [comment]
@aubincleme : How long to deploy cdn.atilla.org ?
Store the content on git seems evil, ideas?

**Comment by AntoineGirard** [comment]
http://cdn.atilla.org/ico/favicon.ico

**Comment by aubincleme** [comment]
@MrChoclate : A git repo for cdn.atilla.org may not be a bad idea; we could hook it up to a CI to deploy domain-wide content.
Btw, @neeev , thank you for making crash web.atilla.org .

**Comment by AntoineGirard** [comment]
@aubincleme web.atilla.org is an old service. Moreover, I didn't touch at this config. This service is disable since several weeks.

**Comment by aubincleme** [comment]
Actually, web.atilla.org is a server alias for www.atilla.org. 

We have issued some problems related to VHost declaration on webstatic's Nginx server a few weeks ago (shop.eistiens.net). This problem is due to a server misconfiguration, that's why web.atilla.org crashed. ... Anyway, the problem is now solved :) !

**Pull request merged**
