### PR TITLE
Add Python dict implementation yaml

### PR DESCRIPTION
**Pull request by flavray**
cc @neeev 

Need to update replay_id and slides link

### CODE REVIEW

**Comment by MrChoclate** [comment]
Upload your slides on git?

**Comment by flavray** [comment]
Done :)

**Comment by MrChoclate** [comment]
https://github.com/hakimel/reveal.js#pdf-export
You can upload the pdf on your git. Ugly but provide an easy way to get a link.

**Comment by flavray** [comment]
I already sent it to @neeev , I think he'll do great with it

**Comment by AntoineGirard** [comment]
I wait the YouTube video id to merge

**Pull request merged**
