### PR TITLE
Added structured data

### PR DESCRIPTION
**Pull request by florent1933**
- breadcrumb
- sitename

### CODE REVIEW

**Comment by MrChoclate** [comment]
BreadcrumbList of one element?

**Comment by florent1933** [comment]
Sitename > categories

**Comment by florent1933** [comment]
We can add a third element but don't know what... Because, name of the conference is already in title

**Comment by Thooms** [comment]
Guys what's the state here? Do you need additional reviewing?

**Comment by MrChoclate** [comment]
Well, we can merge it if we plan to add breadcrumb to talks/formation.
Otherwise it is poor information in my opinion

**Comment by florent1933** [comment]
@MrChoclate : so, do you prefer an URL instead of breadcrumbs? It's not very user friendly...

We can add a second item (or third, it depends) like watch 

YouTube does like that.

**Comment by MrChoclate** [comment]
I vote for breadcrumbs if we add another item in `itemListElement`.

**Comment by florent1933** [comment]
We can add Watch or discover
Le 29 nov. 2015 22:57, "Clément VILLAIN" notifications@github.com a
écrit :

**Comment by florent1933** [comment]
So?

**Comment by florent1933** [comment]
Is it possible to have an answer?

**Comment by florent1933** [comment]
?

**Comment by florent1933** [comment]
This is a long PR, 21 days...

**Pull request merged**
